mensageria.habilitada=true
mensageria.api.baseUrl=http://localhost:8082
mensageria.api.eventosPath=/api/mensageria/eventos
mensageria.websocket.path=/ws-fretes
mensageria.websocket.topic=/topic/fretes
mensageria.origem=SISTEMA_FRETES_WEB
mensageria.lote.maxEventos=50
mensageria.api.connectTimeoutMs=5000
mensageria.api.readTimeoutMs=7000
